const hospitalNames: string[] = [
    "City General Hospital",
    "St. Luke's Medical Center",
    "Mercy Health Clinic",
    "Pine Ridge Community Hospital",
    "Oak Valley Regional Hospital",
    "Sunrise Medical Center",
    "Westwood General",
    "Grandview Hospital",
    "Hopewell Medical Institute",
    "North Star Health System",
    "Riverside County Hospital",
    "Evergreen General",
    "Memorial Central Hospital",
    "University Medical Center",
    "Cedar Sinai Hospital",
    "Bayview Medical Center",
    "Trinity Health Services",
    "Greenfield Community Hospital",
    "Pleasant Valley Hospital",
    "The Good Samaritan Hospital",
    "Crestwood Medical Center",
    "Blue Mountain Clinic",
    "Central City Hospital",
    "St. Jude's Children's Hospital",
    "Lakeside General",
    "Elmwood Medical Park",
    "Royal Victoria Hospital",
    "Parkside Health Center",
    "Aspen Grove Medical",
    "Harborview General Hospital",
    "The Metropolitan Hospital",
    "County Line Medical Center",
    "Golden Gate Regional",
    "Silver Creek Hospital",
    "Redwood Memorial",
    "Valley Presbyterian Hospital",
    "Children's National Hospital",
    "Summit Regional Medical Center",
    "Oceanfront Health Institute",
    "Heartland Community Hospital",
];

const reportTypes: string[] = [
    "Hypertension",
    "Diabetes Mellitus",
    "Asthma",
    "Chronic Obstructive Pulmonary Disease (COPD)",
    "Coronary Artery Disease",
    "Stroke",
    "Cancer",
    "Tuberculosis",
    "Pneumonia",
    "COVID-19",
    "HIV/AIDS",
    "Arthritis",
    "Depression",
    "Anxiety Disorder",
    "Schizophrenia",
    "Epilepsy",
    "Migraine",
    "Gastroenteritis",
    "Peptic Ulcer",
    "Liver Cirrhosis",
    "Kidney Failure",
    "Urinary Tract Infection (UTI)",
    "Malaria",
    "Dengue Fever",
    "Typhoid",
    "Anemia",
    "Obesity",
    "Hypothyroidism",
    "Hyperthyroidism",
];

const doctorNames: string[] = [
    "Dr. Aarav Sharma",
    "Dr. Aditi Patel",
    "Dr. Akash Mehra",
    "Dr. Alok Verma",
    "Dr. Amrita Singh",
    "Dr. Ananya Iyer",
    "Dr. Anil Reddy",
    "Dr. Arjun Malhotra",
    "Dr. Bhavna Kapoor",
    "Dr. Chirag Desai",
    "Dr. Deepak Nair",
    "Dr. Divya Khanna",
    "Dr. Gaurav Bansal",
    "Dr. Harshita Jain",
    "Dr. Ishaan Roy",
    "Dr. Jatin Agarwal",
    "Dr. Kavita Menon",
    "Dr. Kiran Gupta",
    "Dr. Lakshmi Nair",
    "Dr. Mahesh Kulkarni",
    "Dr. Manisha Choudhary",
    "Dr. Neha Sinha",
    "Dr. Nikhil Saxena",
    "Dr. Pallavi Joshi",
    "Dr. Prakash Mishra",
    "Dr. Priya Deshmukh",
    "Dr. Rahul Kapoor",
    "Dr. Rajesh Sharma",
    "Dr. Rekha Pandey",
    "Dr. Rishi Malhotra",
    "Dr. Rohit Tandon",
    "Dr. Sakshi Bhatia",
    "Dr. Sameer Khan",
    "Dr. Sanjay Patel",
    "Dr. Shalini Verma",
    "Dr. Sneha Reddy",
    "Dr. Suresh Menon",
    "Dr. Tanya Arora",
    "Dr. Varun Krishnan",
    "Dr. Vikram Chauhan",
];

export { hospitalNames, reportTypes, doctorNames };
